### ISSUE TITLE
滚动连续吸顶里面的 demo

### ISSUE THREAD

**Issue by shoyuf** [zuopf769/notebook#1]
页面里连惯性滚动都没有?是不能加还是有 bug?

**Comment by zuopf769** [comment]
在ios的webview里面window.onscroll事件不会实时触发，所以要是实时去计算吸顶就实现不了，只有当惯性滚动停止时，才会触发onscroll事件

**Comment by shoyuf** [comment]
惯性滚动的 bug 在 WKWebview 应该已经修复了,你试下 iOS9+的 Safari 还是否有这个 bug?
[demo](https://codepen.io/CarterLi/full/PNjwwq)

**Comment by zuopf769** [comment]
WKWebview内核的webview已经修复了，但是各种UC、手百不是WKWebview
